#!/bin/bash

## audio
if ! pgrep -x "pipewire" > /dev/null; then
	gentoo-pipewire-launcher &
  else
  	pkill pipewire; gentoo-pipewire-launcher restart > /dev/null 2>&1 &
fi

# networking
nm-applet --indicator &

# waybar + notifications
#~/.config/hypr/waybar/start
~/.config/hypr/dwmbar/start
swaync
